version: "1.0"
info:
  model: int-scaffold
packages:
- name: MessagingImportProject
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
